version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm install express --save
      - node app.js # Replace with your actual build script if needed

artifacts:
  files:
    - '**/*'